Fix issue inside Jenkinsfile6

diff --git a/jenkins/jenkins-pipelines/Jenkinsfile b/jenkins/jenkins-pipelines/Jenkinsfile
--- a/jenkins/jenkins-pipelines/Jenkinsfile
+++ b/jenkins/jenkins-pipelines/Jenkinsfile
@@ -71,26 +71,24 @@ pipeline {
         stage('Deploy to EC2') {
             steps {
                 sh '''
-                    echo "Connecting to EC2 and deploying container..."
                     AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
                     ECR_URI="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO"
 
                     ssh -o StrictHostKeyChecking=no -i $SSH_KEY_PATH ubuntu@$EC2_HOST << 'EOF'
-                        echo "Pulling latest image and restarting container..."
+                        if ! command -v aws &> /dev/null; then
+                            sudo apt update -y
+                            sudo apt install -y awscli
+                        fi
 
-                        # Login and pull the latest image
                         sudo docker login -u AWS -p $(aws ecr get-login-password --region $AWS_REGION) $ECR_URI
                         sudo docker pull $ECR_URI:$IMAGE_TAG
 
-                        #Stop and remove any container using port 80 (if exists)
-                        sudo docker ps -q --filter "publish=80" | grep -q . && \
-                        sudo docker stop $(sudo docker ps -q --filter "publish=80") && \
-                        sudo docker rm $(sudo docker ps -q --filter "publish=80")
+                        if sudo docker ps -q --filter "name=backend-app" | grep -q .; then
+                            sudo docker stop backend-app
+                            sudo docker rm backend-app
+                        fi
 
-                        # Run new backend container
                         sudo docker run -d -p 80:5000 --name backend-app $ECR_URI:$IMAGE_TAG
-
-                        echo "Deployment done successfully!"
                     EOF
                 '''
             }
@@ -99,10 +97,10 @@ pipeline {
 
     post {
         success {
-            echo "Deployment completed successfully!"
+            echo "Deployment completed successfully."
         }
         failure {
-            echo "Build or deployment failed — check logs above."
+            echo "Build or deployment failed."
         }
         always {
             cleanWs()
