Fix issue inside Jenkinsfile

diff --git a/jenkins/jenkins-pipelines/Jenkinsfile b/jenkins/jenkins-pipelines/Jenkinsfile
--- a/jenkins/jenkins-pipelines/Jenkinsfile
+++ b/jenkins/jenkins-pipelines/Jenkinsfile
@@ -19,7 +19,8 @@ pipeline {
         stage('Install Dependencies') {
             steps {
                 dir("${APP_DIR}") {
-                    sh '''
+                    sh '''#!/bin/bash
+                        set -e
                         python3 -m venv venv
                         source venv/bin/activate
                         pip install --upgrade pip
@@ -32,7 +33,8 @@ pipeline {
         stage('Run Tests') {
             steps {
                 dir("${APP_DIR}") {
-                    sh '''
+                    sh '''#!/bin/bash
+                        set -e
                         source venv/bin/activate
                         pytest tests/ --maxfail=1 --disable-warnings -q
                     '''
@@ -43,7 +45,8 @@ pipeline {
         stage('Build Docker Image') {
             steps {
                 dir("${APP_DIR}") {
-                    sh '''
+                    sh '''#!/bin/bash
+                        set -e
                         docker build -t $ECR_REPO:$IMAGE_TAG .
                     '''
                 }
@@ -53,7 +56,8 @@ pipeline {
         stage('Login & Push to ECR') {
             steps {
                 withAWS(credentials: 'aws-credentials', region: "${AWS_REGION}") {
-                    sh '''
+                    sh '''#!/bin/bash
+                        set -e
                         AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
                         ECR_URI="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO"
 
@@ -72,7 +76,8 @@ pipeline {
             steps {
                 dir('terraform') {
                     withAWS(credentials: 'aws-credentials', region: "${AWS_REGION}") {
-                        sh '''
+                        sh '''#!/bin/bash
+                            set -e
                             terraform init -input=false
                             terraform apply -auto-approve -input=false
                         '''
@@ -84,10 +89,10 @@ pipeline {
 
     post {
         success {
-            echo "✅ Deployment completed successfully!"
+            echo "Deployment completed successfully!"
         }
         failure {
-            echo "❌ Build or deployment failed — check logs above."
+            echo "Build or deployment failed — check logs above."
         }
         always {
             cleanWs()
